src/org/Bundle/QuinielaBundle/Entity/Pais.php
<?php

namespace org\Bundle\QuinielaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Pais
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Pais
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255)
     */
    private $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="bandera", type="string", length=255)
     */
    private $bandera;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Pais
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    public function getNombreCorto(){

        if(strlen($this->nombre)>8){
            return substr ( $this->nombre , 0 ,8 )."...";
        }else{
            return $this->nombre;
        }

    }

    /**
     * Set bandera
     *
     * @param string $bandera
     * @return Pais
     */
    public function setBandera($bandera)
    {
        $this->bandera = $bandera;

        return $this;
    }

    /**
     * Get bandera
     *
     * @return string 
     */
    public function getBandera()
    {
        return $this->bandera;
    }
}

src/org/Bundle/QuinielaBundle/Entity/Partido.php
<?php

namespace org\Bundle\QuinielaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Partido
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Partido
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="numPartido", type="smallint")
     */
    private $numPartido;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fecha", type="datetime")
     */
    private $fecha;

    /**
     * @var \stdClass
     *
     * @ORM\ManyToOne(targetEntity="Pais", inversedBy="id")
     * @ORM\JoinColumn(name="PaisHome", referencedColumnName="id")
     */
    private $paisHome;

    /**
     * @var \stdClass
     *
     * @ORM\ManyToOne(targetEntity="Pais", inversedBy="id")
     * @ORM\JoinColumn(name="PaisVist", referencedColumnName="id")
     */
    private $paisVisitante;

    /**
     * @var integer
     *
     * @ORM\Column(name="home_score", type="smallint")
     */
    private $homeScore;

    /**
     * @var integer
     *
     * @ORM\Column(name="vist_score", type="smallint")
     */
    private $vistScore;

    /**
     * @var integer
     *
     * @ORM\Column(name="home_penal", type="smallint")
     */
    private $homePenal;

    /**
     * @var integer
     *
     * @ORM\Column(name="vist_penal", type="smallint")
     */
    private $vistPenal;

    /**
     * @var \stdClass
     *
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="id")
     * @ORM\JoinColumn(name="Usuario", referencedColumnName="id")
     */
    private $idUsuario;

    /**
     * @var boolean
     *
     * @ORM\Column(name="jugado", type="boolean")
     */
    private $jugado;

    private $realVisitante;

    private $realHome;

    private $puntaje;

    private $color;

    public function getColor(){
        if(!$this->jugado){
            return "#eee";
        }

        return $this->color;
    }

    public function getRealHome(){
        if(!$this->jugado){
            return "-";
        }
        return $this->realHome;
    }

    public function getRealVisitante(){
        if(!$this->jugado){
            return "-";
        }
        return $this->realVisitante;
    }

    public function getPuntaje(){

        if(!$this->jugado){
            return 0;
        }
        return $this->puntaje;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set numPartido
     *
     * @param integer $numPartido
     * @return Partido
     */
    public function setNumPartido($numPartido)
    {
        $this->numPartido = $numPartido;

        return $this;
    }

    /**
     * Get numPartido
     *
     * @return integer 
     */
    public function getNumPartido()
    {
        return $this->numPartido;
    }

    /**
     * Set fecha
     *
     * @param \DateTime $fecha
     * @return Partido
     */
    public function setFecha($fecha)
    {
        $this->fecha = $fecha;

        return $this;
    }

    /**
     * Get fecha
     *
     * @return \DateTime 
     */
    public function getFecha()
    {
        return $this->fecha;
    }

    /**
     * Set paisHome
     *
     * @param \stdClass $paisHome
     * @return Partido
     */
    public function setPaisHome($paisHome)
    {
        $this->paisHome = $paisHome;

        return $this;
    }

    /**
     * Get paisHome
     *
     * @return \stdClass 
     */
    public function getPaisHome()
    {
        return $this->paisHome;
    }

    /**
     * Set paisVisitante
     *
     * @param \stdClass $paisVisitante
     * @return Partido
     */
    public function setPaisVisitante($paisVisitante)
    {
        $this->paisVisitante = $paisVisitante;

        return $this;
    }

    /**
     * Get paisVisitante
     *
     * @return \stdClass 
     */
    public function getPaisVisitante()
    {
        return $this->paisVisitante;
    }

    /**
     * Set homeScore
     *
     * @param integer $homeScore
     * @return Partido
     */
    public function setHomeScore($homeScore)
    {
        $this->homeScore = $homeScore;

        return $this;
    }

    
    public function getHomeScore2()
    {
        return $this->homeScore ;
    }

      public function getVistScore2()
    {
   
        return $this->vistScore;
    }

    public function getHomeScore()
    {
        if(!$this->jugado){
            return "-";
        }

        return $this->homeScore ;
    }

    /**
     * Set vistScore
     *
     * @param integer $vistScore
     * @return Partido
     */
    public function setVistScore($vistScore)
    {
        $this->vistScore = $vistScore;

        return $this;
    }

    /**
     * Get vistScore
     *
     * @return integer 
     */
    public function getVistScore()
    {
        if(!$this->jugado){
            return "-";
        }
        return $this->vistScore;
    }

    /**
     * Set homePenal
     *
     * @param integer $homePenal
     * @return Partido
     */
    public function setHomePenal($homePenal)
    {

        $this->homePenal = $homePenal;

        return $this;
    }

    /**
     * Get homePenal
     *
     * @return integer 
     */
    public function getHomePenal()
    {
       if(!$this->jugado){
        return "(-)";
    }
    return "("+$this->homePenal+")";
}

    /**
     * Set vistPenal
     *
     * @param integer $vistPenal
     * @return Partido
     */
    public function setVistPenal($vistPenal)
    {

        $this->vistPenal = $vistPenal;

        return $this;
    }

    /**
     * Get vistPenal
     *
     * @return integer 
     */
    public function getVistPenal()
    {
       if(!$this->jugado){
        return "(-)";
    }
    return "("+$this->vistPenal+")";
}

    /**
     * Set idUsuario
     *
     * @param \stdClass $idUsuario
     * @return Partido
     */
    public function setIdUsuario($idUsuario)
    {
        $this->idUsuario = $idUsuario;

        return $this;
    }

    /**
     * Get idUsuario
     *
     * @return \stdClass 
     */
    public function getIdUsuario()
    {
        return $this->idUsuario;
    }

    public function getJugado()
    {
        return $this->jugado;
    }


    public function calcularPuntaje(Partido $partido){
        if($this->paisVisitante == $partido->paisVisitante ||
           $this->paisHome == $partido->paisHome){
            $this->realVisitante = $partido->vistScore;
        $this->realHome = $partido->homeScore;
        $this->jugado = $partido->jugado;
        $this->fecha = $partido->fecha;

        if($partido->homeScore == $this->homeScore && 
         $partido->vistScore == $this->vistScore){
            $this->puntaje = 3;
            $this->color = "#3EA99F";
    }else if(($partido->homeScore > $partido->vistScore && 
     $this->homeScore > $this->vistScore) || ($partido->homeScore < $partido->vistScore && 
     $this->homeScore < $this->vistScore)){
        $this->puntaje = 1;
        $this->color = "#FFF380";
    }else if($partido->homeScore == $partido->vistScore && 
      $this->homeScore == $this->vistScore){
        $this->puntaje = 1;
        $this->color = "#FFF380";
    }else {
        $this->color = "#E77471";
        $this->puntaje =0;
    }


}
}

}

src/org/Bundle/QuinielaBundle/Controller/InicioController.php
<?php

namespace org\Bundle\QuinielaBundle\Controller;

use Org\Bundle\QuinielaBundle\Entity\Usuario;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class InicioController extends Controller
{
    /**
     * @Route("/", name="q_index")
     * @Template()
     */
    public function indexAction()
    {



    	$repository = $this->getDoctrine()->getRepository('orgQuinielaBundle:Usuario');

    	$usuarios = $repository->findAll();    

    	$usuarioMaster = $repository->find(999);


    	foreach ($usuarios as $usuario) {
    		$usuario->calcularPuntaje($usuarioMaster);
    	}

    	usort($usuarios, array($this, "cmp"));

    	return array('usuario' =>$usuarioMaster,'usuarios' =>$usuarios);
    }


    /**
     * @Route("/user/{id}", name="q_user")
     * @Template()
     */
    public function userAction($id)
    {

    	$repository = $this->getDoctrine()->getRepository('orgQuinielaBundle:Usuario');

    	$usuarios = $repository->findAll();

    	$usuarioMaster = $repository->find(999);
    	$usuario = $repository->find($id);
    	$usuario->calcularPuntaje($usuarioMaster);

    	foreach ($usuarios as $usuariotemp) {
    		$usuariotemp->calcularPuntaje($usuarioMaster);
    	}    	

    	usort($usuarios,array($this, "cmp"));

    	return array('usuario' =>$usuario, 'usuarios' =>$usuarios);
    }

    function cmp(Usuario $a,Usuario $b)
    {
    	return $a->getPuntos() < $b->getPuntos();
    }

}

src/org/Bundle/QuinielaBundle/Resources/views/Inicio/index.html.twig
{% extends "orgQuinielaBundle::layout.html.twig" %}

{% block title %}orgQuinielaBundle:Inicio:index{% endblock %}

{% block navbar %}

	<ul>
	{% for item in usuarios if item.id != 999 %}
		<li><a href="{{ path('q_user', {'id':item.id })}}">{{ item.puntos }} - {{ item.nombre}}</a></li>
    {% endfor %}
    </ul>

{% endblock %}

{% block content %}
	<h2><a href="#">Clasificatoria</a></h2>
	<table class="resultados2" style="float: left;width:290px;margin-right:10px">
		{% for item in usuario.partidos if 49 > item.numPartido %}
			<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="90px">{{ item.fecha|date('j/m/Y h:i') }}</td>
			<td width="80px" style="text-align:right">{{item.paisHome.nombreCorto}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore}}</td>
			<td width="20px">{{item.vistScore}}</td>
			<td width="80px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombreCorto}}</td>
			</tr>

			{% if (loop.index % 24) ==  0 %}

			</table>
			<table class="resultados2" style="display:inline-block;width:290px">

			{% endif %}


		{% endfor %}		
	</table>

	<h2><a href="#">8vos de Final</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 49 <= item.numPartido and item.numPartido < 57 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="90px">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="80px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore}}</td>
			<td width="20px">{{item.vistScore}}</td>
			<td width="80px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
		</tr>

		{% endfor %}		
	</table>

	<h2><a href="#">4tos de Final</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 57 <= item.numPartido and item.numPartido < 61 %}


	
		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="90px">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="80px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore}}</td>
			<td width="20px">{{item.vistScore}}</td>
			<td width="80px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
		</tr>

		{% endfor %}		
	</table>


	<h2><a href="#">SemiFinal</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 61 <= item.numPartido and item.numPartido < 63 %}



		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="90px">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="80px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore}}</td>
			<td width="20px">{{item.vistScore}}</td>
			<td width="80px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
		</tr>

		{% endfor %}		
	</table>



	<h2><a href="#">Tercer Lugar</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 63 <= item.numPartido and item.numPartido < 64 %}


	<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="90px">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="80px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore}}</td>
			<td width="20px">{{item.vistScore}}</td>
			<td width="80px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
		</tr>

		{% endfor %}		
	</table>

	<h2><a href="#">Final</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 64 <= item.numPartido and item.numPartido < 65 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="90px">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="80px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore}}</td>
			<td width="20px">{{item.vistScore}}</td>
			<td width="80px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
		</tr>

		{% endfor %}		
	</table>

{% endblock %}

src/org/Bundle/QuinielaBundle/Resources/views/Inicio/user.html.twig
{% extends "orgQuinielaBundle::layout.html.twig" %}

{% block title %}orgQuinielaBundle:Inicio:index{% endblock %}

{% block navbar %}

	<ul>
	{% for item in usuarios if item.id != 999 %}
		<li><a href="{{ path('q_user', {'id':item.id })}}">{{ item.puntos }} - {{ item.nombre}}</a></li>
    {% endfor %}
    </ul>

{% endblock %}

{% block content %}
	<h1>{{usuario.nombre}} - {{ usuario.puntos}}</h1>
	<h2><a href="#">Clasificatoria</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if item.numPartido < 49 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="180px" style="text-align:right">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="160px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore2}}</td>
			<td width="20px">{{item.vistScore2}}</td>
			<td width="160px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
			<td>{{ item.RealHome}}</td>
			<td>{{ item.RealVisitante}}</td>
			<td style="background-color:{{item.color}};">{{ item.puntaje}}</td>
		</tr>

		{% endfor %}		
	</table>


	<h2><a href="#">8vos de Final</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 49 <= item.numPartido and item.numPartido < 57 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="180px" style="text-align:right">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="160px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore2}}</td>
			<td width="20px">{{item.vistScore2}}</td>
			<td width="160px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
			<td>{{ item.RealHome}}</td>
			<td>{{ item.RealVisitante}}</td>
			<td style="background-color:{{item.color}};">{{ item.puntaje}}</td>
		</tr>

		{% endfor %}		
	</table>

	<h2><a href="#">4tos de Final</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 57 <= item.numPartido and item.numPartido < 61 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="180px" style="text-align:right">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="160px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore2}}</td>
			<td width="20px">{{item.vistScore2}}</td>
			<td width="160px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
			<td>{{ item.RealHome}}</td>
			<td>{{ item.RealVisitante}}</td>
			<td style="background-color:{{item.color}};">{{ item.puntaje}}</td>
		</tr>

		{% endfor %}		
	</table>


	<h2><a href="#">SemiFinal</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 61 <= item.numPartido and item.numPartido < 63 %}



		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="180px" style="text-align:right">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="160px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore2}}</td>
			<td width="20px">{{item.vistScore2}}</td>
			<td width="160px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
			<td>{{ item.RealHome}}</td>
			<td>{{ item.RealVisitante}}</td>
			<td style="background-color:{{item.color}};">{{ item.puntaje}}</td>
		</tr>

		{% endfor %}		
	</table>



	<h2><a href="#">Tercer Lugar</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 63 <= item.numPartido and item.numPartido < 64 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="180px" style="text-align:right">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="160px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore2}}</td>
			<td width="20px">{{item.vistScore2}}</td>
			<td width="160px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
			<td>{{ item.RealHome}}</td>
			<td>{{ item.RealVisitante}}</td>
			<td style="background-color:{{item.color}};">{{ item.puntaje}}</td>
		</tr>

		{% endfor %}		
	</table>

	<h2><a href="#">Final</a></h2>
	<table class="resultados">
		{% for item in usuario.partidos if 64 <= item.numPartido and item.numPartido < 65 %}


		<tr>
			<td class="pos">{{ item.numPartido }}</td>
			<td width="180px" style="text-align:right">{{ item.fecha|date(' l j/m/Y h:i') }}</td>
			<td width="160px" style="text-align:right">{{item.paisHome.nombre}} <img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisHome.bandera}}"></td>
			<td width="20px">{{item.homeScore2}}</td>
			<td width="20px">{{item.vistScore2}}</td>
			<td width="160px" style="text-align:left"><img class="logo" style="vertical-align:middle"  height="10" width="15"src="{{ asset('bundles/orgquiniela/images/flags/')}}{{item.paisVisitante.bandera}}"> {{item.paisVisitante.nombre}}</td>
			<td>{{ item.RealHome}}</td>
			<td>{{ item.RealVisitante}}</td>
			<td style="background-color:{{item.color}};">{{ item.puntaje}}</td>
		</tr>

		{% endfor %}		
	</table>



{% endblock %}